#docker compose file for backend and frontend


services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
  
  frontend:
    build: ./app
    ports:
      - "3000:3000"
